[project]
name = "deepagents"
version = "0.3.1"
description = "General purpose 'deep agent' with sub-agent spawning, todo list capabilities, and mock file system. Built on LangGraph."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
authors = [
    { name = "熊湘毅", email = "1666526339@qq.com" }
]
dependencies = [
    "langchain-anthropic>=1.2.0",
    "langchain-google-genai",
    "langchain>=1.1.0",
    "langchain-core>=1.1.0",
    "wcmatch",
]

[build-system]
requires = ["setuptools>=73.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# 包在 libs/deepagents 子目录中
package-dir = {"" = "libs/deepagents"}
packages = ["deepagents"]

[tool.setuptools.package-data]
"*" = ["py.typed", "*.md"]
